#  Step 1 → checkout code
#  Step 2 → install java
#  Step 3 → build application
#  Step 4 → deploy
#  @v2 -> version 2.x.x
#  @V3 -> version 3.x.x
#  @v4 -> version 4.x.x

name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '23'

      - name: Build
        run: mvn clean package

